title: <p align="center"> Yosuaaa Saputra </p>

logo: "/images/logosamplecircle.png?raw=true"
#logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/2023 Saputra,Yosua_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/yosua-saputra/">LinkedIn</a> |
  <a href="https://github.com/ohayosua">GitHub</a>
  </p>
  
  <p align="justify">
  Data analyst with over a year of experience. Proficient in SQL, Tableau, Python, and Excel.
  Currently expanding my knowledge of utilizing ML models and automation processes for valuable insights and further data analysis.
  <br><br>
  In my previous employment I have worked with deriving insights from customer subscription based data, building dashboards, improving operational effficiency, and conducting data quality assurance.  
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
