title: <p align="center"> Yosua Saputra </p>

logo: "/images/Bridge Circle Profile Pic.png" 
#logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Yosua Saputra, Data Resume 2024.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/yosua-saputra/">LinkedIn</a> |
  <a href="https://github.com/ohayosua">GitHub</a>
  </p>
  
  <p align="justify">
  Data analyst with over a year of experience. Proficient in SQL, Tableau, Python, and Excel.
  Currently expanding my knowledge of utilizing ML models and automation processes for valuable insights and further data analysis.
  <br><br>
  I have experience working on deriving insights from customer subscription based data, building dashboards, improving operational effficiency, and conducting data quality assurance.  
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
